"""Ajustada a coluna para não permitir null

Revision ID: 576336650d5c
Revises: 26f7038dfb58
Create Date: 2025-12-02 09:54:03.142433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576336650d5c'
down_revision = '26f7038dfb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
